In [3]:
import numpy as np
from sklearn.datasets import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
iris = datasets.load_iris()
X = iris.data 
y = iris.target 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 100.00%


In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
df = pd.read_csv('/home/ksb/fruit_dataset.csv')
print(df)
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

    Weight  Size Category
0      150   7.0    Apple
1      160   7.2    Apple
2      145   6.8    Apple
3      170   7.5    Apple
4      155   7.1    Apple
5      165   7.3    Apple
6      120  15.0   Banana
7      110  14.5   Banana
8      125  15.5   Banana
9      115  14.8   Banana
10     130  16.0   Banana
11     118  15.2   Banana
12     180   8.0   Orange
13     190   8.5   Orange
14     175   7.8   Orange
15     200   8.8   Orange
16     185   8.2   Orange
17     195   8.6   Orange
Accuracy: 100.00%


In [2]:
#confusion metrics
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

data=load_iris()

X=data.data
y=data.target
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

nb_classifier=GaussianNB()
nb_classifier.fit(X_train,y_train)
y_pred=nb_classifier.predict(X_test)
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:",cm)

Confusion Matrix: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [7]:
# Confusion Matrix with diiferent dataset

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
data = pd.read_csv('/home/ksb/fruit_dataset.csv')
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[3 0]
 [0 1]]


In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
df = pd.read_csv('/home/ksb/fruit_dataset.csv')
print(df)
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
new_data = [[150, 7]]
prediction = nb_classifier.predict(new_data)
print("Predicted Fruit:", prediction[0])

    Weight  Size Category
0      150   7.0    Apple
1      160   7.2    Apple
2      145   6.8    Apple
3      170   7.5    Apple
4      155   7.1    Apple
5      165   7.3    Apple
6      120  15.0   Banana
7      110  14.5   Banana
8      125  15.5   Banana
9      115  14.8   Banana
10     130  16.0   Banana
11     118  15.2   Banana
12     180   8.0   Orange
13     190   8.5   Orange
14     175   7.8   Orange
15     200   8.8   Orange
16     185   8.2   Orange
17     195   8.6   Orange
Accuracy: 100.00%
Predicted Fruit: Apple
