In [1]:
import numpy as np
x=np.array([[7,4],[1,2]])
y=np.array([[3,7],[1,2]])
A = x + y
D = x - y
M = x * y
m = np.dot(x,y)
transpose=x.T
print ("Addition:")
print(A)
print("\nSubtraction:")
print(D)
print("\nElement wise multiplication:")
print(M)
print("\nMatrix multipliction:")
print(m)
print("\nTranspose:")
print(transpose)

Addition:
[[10 11]
 [ 2  4]]

Subtraction:
[[ 4 -3]
 [ 0  0]]

Element wise multiplication:
[[21 28]
 [ 1  4]]

Matrix multipliction:
[[25 57]
 [ 5 11]]

Transpose:
[[7 1]
 [4 2]]


In [3]:
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT=np.linalg.svd(X)
n_components = 2
X_reconstructed = np.dot(U[:, :n_components], np.dot(np.diag(S[:n_components]), VT[:n_components, :]))
print("Original Matrix:")
print(X)
print("\n Reconstructed Matrix(with reduced dimensions):")
print(X_reconstructed)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Reconstructed Matrix(with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
